server:
  port: ${SERVER_PORT:8080}

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources/
  application:
    name: ct-nexxus

  datasource:
    url: jdbc:postgresql://ep-icy-frost-acfazn43-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_GVYyRM6uq9WK
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
    show-sql: true
    open-in-view: false


  thymeleaf:
    cache: false

  # ====== EMAIL (SMTP) ======
  mail:
    host: smtp.gmail.com
    port: 587
    username: ctnexxus@gmail.com
    password: ojhl biaw ujoy hefw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Configs do sistema
ctnexxus:
  lembrete:
    dias-antes: 2,1,0
    hora-envio: "09:00"
  security:
    admin-user: "admin"
    admin-pass: "admin123" # IMPORTANTE: Altere esta senha para o ambiente de produção!

logging:
  level:
    org.thymeleaf: DEBUG
    org.springframework.web: TRACE
    org.springframework.web.servlet: TRACE
